//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhanPhanBon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public int id { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<bool> isCoMat { get; set; }
        public Nullable<bool> isVang { get; set; }
        public int NhanVien { get; set; }
    
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
