//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhanPhanBon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanBon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanBon()
        {
            this.PhanBon_KH = new HashSet<PhanBon_KH>();
        }
    
        public int IDPhanBon { get; set; }
        public string TenPhanBon { get; set; }
        public int LoaiPhanBon { get; set; }
        public int Gia { get; set; }
        public bool isDelete { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual LoaiPhanBon LoaiPhanBon1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanBon_KH> PhanBon_KH { get; set; }
    }
}
